# Generated by Django 2.0 on 2020-07-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20200723_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='last_name',
        ),
        migrations.AddField(
            model_name='agent',
            name='name',
            field=models.CharField(default='Agent', max_length=128),
            preserve_default=False,
        ),
    ]
