# Generated by Django 2.0 on 2020-07-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20200722_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.Agent'),
        ),
    ]
