# Generated by Django 2.2 on 2020-10-05 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_call_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_duration',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(limit_value=0.0)]),
        ),
        migrations.AddField(
            model_name='call',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
