# Generated by Django 2.2 on 2020-10-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_auto_20201005_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='comment',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
