# Generated by Django 2.2 on 2020-10-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentactivity',
            options={'verbose_name': 'Agent Activity', 'verbose_name_plural': 'Agent Activities'},
        ),
    ]
