# Generated by Django 2.0 on 2020-07-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_title', models.CharField(blank=True, max_length=64)),
                ('company', models.CharField(blank=True, max_length=128)),
                ('c_emp_range', models.CharField(blank=True, choices=[('1-10', '1 to 10'), ('11-50', '11 to 50'), ('51-200', '51 to 200'), ('201-500', '201 to 500'), ('501-1000', '501 to 1000'), ('1001-5000', '1001 to 5000'), ('5001-10000', '5001 to 10000'), ('10000+', '10000+')], max_length=32, verbose_name='Employee Range')),
                ('c_website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('industry', models.CharField(blank=True, max_length=128)),
                ('address_1', models.CharField(blank=True, max_length=96)),
                ('address_2', models.CharField(blank=True, max_length=96)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('data_list', models.CharField(default='Unknown', max_length=32)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Branch')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Campaign')),
            ],
        ),
        migrations.AddField(
            model_name='prospect',
            name='prospect_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospects.ProspectList'),
        ),
    ]
