# Generated by Django 2.0 on 2020-07-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='data_list',
        ),
    ]
