# Generated by Django 2.0 on 2020-07-27 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_remove_prospect_data_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectlist',
            name='csv_file',
            field=models.FileField(default='', upload_to='campaigns/csv_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
            preserve_default=False,
        ),
    ]
