# Generated by Django 2.0 on 2020-07-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_prospectlist_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='c_website',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.CharField(default='-', max_length=128),
            preserve_default=False,
        ),
    ]
