# Generated by Django 2.0 on 2020-07-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0004_auto_20200727_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
