# Generated by Django 2.2 on 2020-07-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0005_auto_20200727_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='c_emp_range',
            field=models.CharField(blank=True, max_length=32, verbose_name='Employee Range'),
        ),
    ]
