# Generated by Django 2.0 on 2020-08-31 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200723_1428'),
        ('prospects', '0006_auto_20200731_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectlist',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Visitor'),
        ),
    ]
