# Generated by Django 2.0 on 2020-07-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('prospects', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AddField(
            model_name='campaignprospectlist',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign'),
        ),
        migrations.AddField(
            model_name='campaignprospectlist',
            name='prospect_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospects.ProspectList'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Branch'),
        ),
    ]
