# Generated by Django 2.0 on 2020-07-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_remove_prospect_data_list'),
        ('campaigns', '0002_auto_20200722_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignProspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospects.Prospect')),
            ],
        ),
    ]
