# Generated by Django 2.0 on 2020-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignprospect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='starting_date',
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default='AC', max_length=2),
        ),
    ]
