# Generated by Django 2.0 on 2020-07-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_campaign_calls_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='script',
        ),
        migrations.AddField(
            model_name='campaign',
            name='consent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='questions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
