# Generated by Django 2.0 on 2020-07-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('campaigns', '0007_campaignprospect_call_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('name', 'branch')},
        ),
    ]
