# Generated by Django 2.2 on 2020-07-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='confirm',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='questions',
            field=models.TextField(verbose_name='Script'),
        ),
    ]
