# Generated by Django 2.2 on 2020-09-23 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20200731_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='notes',
            new_name='rebuttal',
        ),
    ]
