# Generated by Django 2.2 on 2020-09-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_auto_20200923_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='asset_name',
            field=models.CharField(default='-', max_length=128),
        ),
    ]
