# Generated by Django 2.0 on 2020-10-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaign_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='timezone_str',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
