# Generated by Django 2.0 on 2022-01-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_auto_20210301_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_domestic',
            field=models.BooleanField(default=False),
        ),
    ]
