# Generated by Django 2.0 on 2022-01-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_campaign_is_domestic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_domestic',
            field=models.CharField(choices=[('IN', 'International'), ('DM', 'Domestic')], default='IN', max_length=2),
        ),
    ]
