# Generated by Django 2.2 on 2021-03-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('from_ist', models.TimeField()),
                ('to_ist', models.TimeField()),
            ],
        ),
    ]
